// Generated by scripts/prepare-stickers.mjs — do not edit by hand.
// Run `npm run stickers` after changing anything in stickers-raw/.

export interface StickerArt {
  src: string
  /** Size of a single frame, in px. */
  width: number
  height: number
  /** 1 for a still drawing; more means the file is a horizontal strip. */
  frames: number
}

export const STICKER_ART = {

} satisfies Record<string, StickerArt>

export type StickerArtName = keyof typeof STICKER_ART
